server:
  port: 0

spring:
  application:
    name: user-service

  zipkin:
    base-url: http://localhost:9411/

  r2dbc:
    url: ${BINGO_DB_URL_R2DBC}
    username: ${BINGO_DB_USER}
    password: ${BINGO_DB_PASS}

  flyway:
    url: ${BINGO_DB_URL}
    user: ${BINGO_DB_USER}
    password: ${BINGO_DB_PASS}
    encoding: UTF-8
    out-of-order: true
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

eureka:
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true