server:
  port: 0

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/bingo
    username: root
    password: 06021988abc

eureka:
  instance:
    prefer-ip-address: true