server:
  port: 0

spring:
  application:
    name: user-service

  zipkin:
    base-url: http://localhost:9411/

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/bingo
    username: root
    password: 06021988abc

eureka:
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true