server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        newbets-in-0:
          group: bets
          destination: invoice-service
    function:
      definition: newBets
  zipkin:
    base-url: http://localhost:9411/

  r2dbc:
    url: ${BINGO_INVOICE_DB_URL_R2DBC}
    username: ${BINGO_INVOICE_DB_USER}
    password: ${BINGO_INVOICE_DB_PASS}

  flyway:
    url: ${BINGO_INVOICE_DB_URL}
    user: ${BINGO_INVOICE_DB_USER}
    password: ${BINGO_INVOICE_DB_PASS}
    encoding: UTF-8
    out-of-order: true
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  application:
    name: invoice-service
  rabbitmq:
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true