server:
  port: 0

spring:

  cloud:
    stream:
      bindings:
        newbets-in-0:
          group: bets
          destination: invoice-service
    function:
      definition: newBets

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/bingo_invoice
    username: root
    password: 06021988abc

  application:
    name: invoice-service

  rabbitmq:
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true









