server:
  port: 0

spring:
  application:
    name: gambling-service
  rabbitmq:
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    prefer-ip-address: true



app:
  registration-money: 500